services:
  caddy:
    image: caddy:latest
    container_name: caddy_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - proxy_net

  shadowsocks:
    image: shadowsocks/shadowsocks-libev:latest # Используем официальный образ libev
    container_name: shadowsocks_proxy
    restart: unless-stopped
    command: ss-server -s [::] -p 8388 -m aes-256-gcm -k ${SS_PASSWORD} --plugin v2ray-plugin --plugin-opts "server;path=${SS_WS_PATH};mux=0;nameserver="1.1.1.1""
    environment:
      - SS_PASSWORD=${SS_PASSWORD}
      - SS_WS_PATH=${SS_WS_PATH}
    networks:
      - proxy_net
    volumes:
      - ./v2ray-plugin_exec:/usr/local/bin/v2ray-plugin:ro

volumes:
  caddy_data:
  caddy_config:

networks:
  proxy_net:
    driver: bridge
