services:
  xray:
    image: teddysun/xray:latest
    container_name: xray_proxy
    restart: unless-stopped
    volumes:
      - ./xray_config.json:/etc/xray/config.json:ro
    ports:
      - "443:443/tcp"
    networks:
      - proxy_net

networks:
  proxy_net:
    driver: bridge
